### ISSUE TITLE
Rootfile system

### ISSUE THREAD

**Issue by schegde** [enclustra-bsp/bsp-xilinx#2]
How could i change the rootfile system from busybox to ubuntu 14.04 corefs for ARM?

**Comment by niklas88** [comment]
This is a bit hacky but works for me. Simply replace the contents of the root file system with those from a similar system. I've successfully done this with the Debian from a BeagleBone Black. Note that you might need to be careful around the whole hard- vs softfload difference.

**Comment by schegde** [comment]
I tried that, but throws up a "no Working init found" error. So I did a manual kernel header and module build and installed them on Ubuntu 14.04 ARM file system, and that worked with the boot files generated from enclustra-BSP.Need to make sure the kernel being used with this file system is of same version or higher than the headers. Thanks for the help!
