### ISSUE TITLE
Documentation link leads to 404

### ISSUE THREAD

**Issue by markus-k** [enclustra-bsp/bsp-xilinx#25]
The link on the README (and website) to the documentation for this BSP now leads to a 404: https://enclustra.github.io/ebe-docs/user-doc-xilinx/index_xilinx.html

It was still there a few weeks ago.

**Comment by dduerner** [comment]
the issue should be fixed by now. If you still see the error 404 page, delete your browser cache and try again.

**Comment by markus-k** [comment]
Thank you, working again!
