### ISSUE TITLE
Linker misses --fix-cortex-a53-843419

### ISSUE THREAD

**Issue by niklas88** [enclustra-bsp/bsp-xilinx#3]
I'm not sure this is relevant for the Zynq-Ultrascale but it might be and also points to a mismatch in the linker version vs other build files.

From the build.log:

    arch/arm64/Makefile:23: ld does not support --fix-cortex-a53-843419; kernel may be susceptible to erratum

**Comment by tgorochowik** [comment]
Hello @niklas88 

Thank you for the report and sorry for ignoring this for such a long time!

Since this was reported we upgraded the toolchains used in the build system and this does not seem to appear anymore, so I will allow myself to close this issue.

Thanks again!
