### ISSUE TITLE
how to Use network ssh enter the board

### ISSUE THREAD

**Issue by wangyuanzhengbighead** [enclustra-bsp/bsp-xilinx#30]
now i can connect serial port to enter linux,
but i want to use cable enter linux with ssh 
how to config it?

**Comment by andreas-buerkler-enclustra** [comment]
Dear wangyuanzhengbighead

SSH access for root user is disabled by default. The easiest way is to create a new user that can be used for SSH access.

This is described in the Build Environment How-To guide in section 4.10.1 (Create New User):
https://download.enclustra.com/public_files/Design_Support/Application%20Notes/Enclustra_Build_Environment_HowToGuide_V02.pdf

**Comment by wangyuanzhengbighead** [comment]
Problem solved
thanks
