### ISSUE TITLE
Performance evaluatio of XU1

### ISSUE THREAD

**Issue by flpm2** [enclustra-bsp/bsp-xilinx#31]
Hi, 
since I don't see any way to test the complete system performance using the current release v1.8.2 (i.e. no support for remote procs / unknown gpu support ). 
Could you please advise on how to obtain meaningful results?

**Comment by tholzsche** [comment]
Hi, this is quite a wide field and with the EBE we provide a very flexible framework which can be extended accordingly. Nevertheless, Petalinux BSPs are currently in work, which allow a somewhat easier integration of the gpu and vcu. Furthermore there are a lot of examples for performance analysis of Xilinx, e.g.: https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/189595724/Zynq+UltraScale+MPSoC+Example+Designs

**Comment by flpm2** [comment]
Hi! Thanks for the reply. In the eclustra case I don't think the petalinux bsp is applicable; the use a MSP430 to readout most of the data. Can you please suggest how to readout the available sensors from /sys instead of vivado ?

**Comment by flpm2** [comment]
According to the [datasheet](https://www.xilinx.com/support/documentation/selection-guides/zynq-ultrascale-plus-product-selection-guide.pdf)of 15EG, it should be 1.5GHz; I tried to set the opp0 to this frequency, but actually it doesn't set it even though it is reported as max frequency. 


`root@mercury-xu1:~# cpufreq-info
cpufrequtils 008: cpufreq-info (C) Dominik Brodowski 2004-2009
Report errors and bugs to cpufreq@vger.kernel.org, please.
analyzing CPU 0:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 500 us.
  hardware limits: 300 MHz - 1.50 GHz
  available frequency steps: 300 MHz, 400 MHz, 600 MHz, 1.50 GHz
  available cpufreq governors: userspace, performance
  current policy: frequency should be within 300 MHz and 1.50 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency is 1.20 GHz (asserted by call to hardware).
analyzing CPU 1:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 500 us.
  hardware limits: 300 MHz - 1.50 GHz
  available frequency steps: 300 MHz, 400 MHz, 600 MHz, 1.50 GHz
  available cpufreq governors: userspace, performance
  current policy: frequency should be within 300 MHz and 1.50 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency is 1.20 GHz (asserted by call to hardware).
analyzing CPU 2:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 500 us.
  hardware limits: 300 MHz - 1.50 GHz
  available frequency steps: 300 MHz, 400 MHz, 600 MHz, 1.50 GHz
  available cpufreq governors: userspace, performance
  current policy: frequency should be within 300 MHz and 1.50 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency is 1.20 GHz (asserted by call to hardware).
analyzing CPU 3:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 500 us.
  hardware limits: 300 MHz - 1.50 GHz
  available frequency steps: 300 MHz, 400 MHz, 600 MHz, 1.50 GHz
  available cpufreq governors: userspace, performance
  current policy: frequency should be within 300 MHz and 1.50 GHz.
                  The governor "performance" may decide which speed to use
                  within this range.
  current CPU frequency is 1.20 GHz (asserted by call to hardware).

`
Can you please suggest how to set it ?

**Comment by tholzsche** [comment]
It actually states up to 1.5GHz. Please check which cpu frequency is expected for your device (Table 28 in https://www.xilinx.com/support/documentation/data_sheets/ds925-zynq-ultrascale-plus.pdf)

Since you work with cpufreq-utils you may want to take a look at https://www.xilinx.com/support/answers/71070.html

**Comment by flpm2** [comment]
Thank you very much! I was having the wrong expectations of my 15EG device (ME-XU1-15EG-2I-D12E).. One last thing that's bothering me is that when I set the RAM to be 4GB instead of 2GB (as suggested in [issue 10]( https://github.com/enclustra-bsp/bsp-xilinx/issues/10)). I start to get ADMA errors from the sd-card when the I/O load increases.

https://paste.ubuntu.com/p/Yw7p4hnPYV/

 Do you have any suggestions what am I doing wrong?  (currently use ubuntu 18 instead of buildroot rootfs)

**Comment by tholzsche** [comment]
This is perhaps caused by a simplification of the reference design, which uses the memory size of the "smallest device". Please check the "DDR Configuration" in Vivado:
* DRAM Device Capacity: 8192
* Row Address Count: 16

**Comment by flpm2** [comment]
Thanks you for the support once again. Now I'm trying to integrate analog-devices kernel 4.19 to try to use the FMC to an ADVR9009 (e.g. similar setup to zcu102 - advr9009); 

However I'm struck on some weird clock error. Do you have any ideas what might be wrong?

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 4.19.0-g3efbf7f19954 (filipm@filip-hp850g7) (gcc version 7.5.0 (Linaro GCC 7.5-2019.12)) #15 SMP Thu Nov 19 13:59:37 EET 2020
[    0.000000] Machine model: Enclustra XU1 SOM
[    0.000000] earlycon: cdns0 at MMIO 0x00000000ff000000 (options '115200n8')
[    0.000000] bootconsole [cdns0] enabled
[    0.000000] cma: Reserved 256 MiB at 0x0000000070000000
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.1 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.1
[    0.000000] percpu: Embedded 22 pages/cpu @(____ptrval____) s51992 r8192 d29928 u90112
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: enabling workaround for ARM erratum 845719
[    0.000000] CPU features: detected: Kernel page table isolation (KPTI)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 516096
[    0.000000] Kernel command line: console=ttycdnss0,115200 rw earlycon rootwait
[    0.000000] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes)
[    0.000000] Inode-cache hash table entries: 131072 (order: 8, 1048576 bytes)
[    0.000000] Memory: 1783960K/2097152K available (8830K kernel code, 570K rwdata, 3624K rodata, 704K init, 500K bss, 51048K reserved, 262144K cma-reserved)
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GIC: Adjusting CPU interface base to 0x00000000f902f000
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] arch_timer: cp15 timer(s) running at 33.33MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x7b0074340, max_idle_ns: 440795202884 ns
[    0.000003] sched_clock: 56 bits at 33MHz, resolution 30ns, wraps every 2199023255543ns
[    0.008269] Console: colour dummy device 80x25
[    0.012393] Calibrating delay loop (skipped), value calculated using timer frequency.. 66.66 BogoMIPS (lpj=133332)
[    0.022668] pid_max: default: 32768 minimum: 301
[    0.027375] Mount-cache hash table entries: 4096 (order: 3, 32768 bytes)
[    0.033918] Mountpoint-cache hash table entries: 4096 (order: 3, 32768 bytes)
[    0.041811] ASID allocator initialised with 32768 entries
[    0.046418] rcu: Hierarchical SRCU implementation.
[    0.051666] smp: Bringing up secondary CPUs ...
[    0.055929] Detected VIPT I-cache on CPU1
[    0.055960] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.056269] Detected VIPT I-cache on CPU2
[    0.056289] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.056582] Detected VIPT I-cache on CPU3
[    0.056601] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.056647] smp: Brought up 1 node, 4 CPUs
[    0.091089] SMP: Total of 4 processors activated.
[    0.095762] CPU features: detected: 32-bit EL0 Support
[    0.102494] CPU: All CPU(s) started at EL2
[    0.104941] alternatives: patching kernel code
[    0.110173] devtmpfs: initialized
[    0.117481] random: get_random_u32 called from bucket_table_alloc.isra.7+0x88/0x180 with crng_init=0
[    0.121875] Registered cp15_barrier emulation handler
[    0.126735] Registered setend emulation handler
[    0.131325] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.140923] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.151990] pinctrl core: initialized pinctrl subsystem
[    0.152833] NET: Registered protocol family 16
[    0.156891] audit: initializing netlink subsys (disabled)
[    0.162080] audit: type=2000 audit(0.104:1): state=initialized audit_enabled=0 res=1
[    0.170131] vdso: 2 pages (1 code @ (____ptrval____), 1 data @ (____ptrval____))
[    0.177076] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.184622] DMA: preallocated 256 KiB pool for atomic allocations
[    0.200672] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.202697] vgaarb: loaded
[    0.204607] SCSI subsystem initialized
[    0.208309] usbcore: registered new interface driver usbfs
[    0.213605] usbcore: registered new interface driver hub
[    0.218884] usbcore: registered new device driver usb
[    0.224073] pps_core: LinuxPPS API ver. 1 registered
[    0.228800] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.237895] PTP clock support registered
[    0.241780] EDAC MC: Ver: 3.0.0
**[    0.245253] zynqmp-ipi ff9905c0.mailbox: No IPI local ID is specified.
[    0.251459] zynqmp-ipi: probe of ff9905c0.mailbox failed with error -22**
[    0.258291] jesd204: found 0 devices and 0 topologies
[    0.263008] FPGA manager framework
[    0.267840] clocksource: Switched to clocksource arch_sys_counter
[    0.272501] VFS: Disk quotas dquot_6.6.0
[    0.276332] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.287483] NET: Registered protocol family 2
[    0.287949] tcp_listen_portaddr_hash hash table entries: 1024 (order: 2, 16384 bytes)
[    0.295260] TCP established hash table entries: 16384 (order: 5, 131072 bytes)
[    0.302514] TCP bind hash table entries: 16384 (order: 6, 262144 bytes)
[    0.309173] TCP: Hash tables configured (established 16384 bind 16384)
[    0.315527] UDP hash table entries: 1024 (order: 3, 32768 bytes)
[    0.321478] UDP-Lite hash table entries: 1024 (order: 3, 32768 bytes)
[    0.327955] NET: Registered protocol family 1
[    0.332381] RPC: Registered named UNIX socket transport module.
[    0.338062] RPC: Registered udp transport module.
[    0.342722] RPC: Registered tcp transport module.
[    0.347392] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.354197] hw perfevents: no interrupt-affinity property for /pmu, guessing.
[    0.361073] hw perfevents: enabled with armv8_pmuv3 PMU driver, 7 counters available
[    0.369465] Initialise system trusted keyrings
[    0.373079] workingset: timestamp_bits=46 max_order=19 bucket_order=0
[    0.380140] NFS: Registering the id_resolver key type
[    0.384460] Key type id_resolver registered
[    0.388567] Key type id_legacy registered
[    0.392551] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.399217] jffs2: version 2.2. (NAND) (SUMMARY)  © 2001-2006 Red Hat, Inc.
[    0.410591] Key type asymmetric registered
[    0.410629] Asymmetric key parser 'x509' registered
[    0.415156] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 246)
[    0.422478] io scheduler noop registered
[    0.426368] io scheduler deadline registered
[    0.430629] io scheduler cfq registered (default)
[    0.435279] io scheduler mq-deadline registered
[    0.439775] io scheduler kyber registered
[    0.444275] Error: Driver 'xilinx-pcie' is already registered, aborting...
[    0.480673] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    0.484559] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.492324] brd: module loaded
[    0.496148] loop: module loaded
[    0.496410] Registered mathworks_ip class
[    0.498328] mtdoops: mtd device (mtddev=name/number) must be supplied
[    0.504376] cdns-spi ff040000.spi: pclk clock not found.
[    0.509805] libphy: Fixed MDIO Bus: probed
[    0.513415] tun: Universal TUN/TAP device driver, 1.6
[    0.518493] CAN device driver interface
[    0.523046] usbcore: registered new interface driver asix
[    0.527604] usbcore: registered new interface driver ax88179_178a
[    0.533644] usbcore: registered new interface driver cdc_ether
[    0.539440] usbcore: registered new interface driver net1080
[    0.545061] usbcore: registered new interface driver cdc_subset
[    0.550942] usbcore: registered new interface driver zaurus
[    0.556487] usbcore: registered new interface driver cdc_ncm
[    0.562575] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.568571] ehci-pci: EHCI PCI platform driver
[    0.573237] usbcore: registered new interface driver uas
[    0.578287] usbcore: registered new interface driver usb-storage
[    0.584281] usbcore: registered new interface driver usbserial_generic
[    0.590730] usbserial: USB Serial support registered for generic
[    0.596702] usbcore: registered new interface driver ftdi_sio
[    0.602407] usbserial: USB Serial support registered for FTDI USB Serial Device
[    0.609675] usbcore: registered new interface driver upd78f0730
[    0.615554] usbserial: USB Serial support registered for upd78f0730
[    0.623083] rtc_zynqmp ffa60000.rtc: rtc core: registered ffa60000.rtc as rtc0
[    0.629002] i2c /dev entries driver
[    0.633584] EDAC MC0: Giving out device to module 1 controller synps_ddr_controller: DEV synps_edac (INTERRUPT)
[    0.642597] EDAC DEVICE0: Giving out device to module edac controller cache_err: DEV edac (POLLED)
[    0.651520] EDAC DEVICE1: Giving out device to module zynqmp-ocm-edac controller zynqmp_ocm: DEV ff960000.memory-controller (INTERRUPT)
[    0.663916] sdhci: Secure Digital Host Controller Interface driver
[    0.669599] sdhci: Copyright(c) Pierre Ossman
[    0.673923] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.679934] ledtrig-cpu: registered to indicate activity on CPUs
[    0.685635] zynqmp_firmware_probe Platform Management API v1.0
[    0.691314] zynqmp_firmware_probe Trustzone version v1.0
[    0.697262] alg: No test for xilinx-keccak-384 (zynqmp-keccak-384)
[    0.702898] alg: No test for xilinx-zynqmp-rsa (zynqmp-rsa)
[    0.708544] usbcore: registered new interface driver usbhid
[    0.713804] usbhid: USB HID core driver
**[    0.719412] zynqmp_fpga_manager pcap: failed to to get pcp ref_clk (-2)
[    0.724193] zynqmp_fpga_manager: probe of pcap failed with error -2**
[    0.730608] pktgen: Packet Generator for packet performance testing. Version: 2.75
[    0.738345] Initializing XFRM netlink socket
[    0.742269] NET: Registered protocol family 10
[    0.746937] Segment Routing with IPv6
[    0.750320] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.756422] NET: Registered protocol family 17
[    0.760522] NET: Registered protocol family 15
[    0.764940] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    0.777988] can: controller area network core (rev 20170425 abi 9)
[    0.783999] NET: Registered protocol family 29
[    0.788369] can: raw protocol (rev 20170425)
[    0.792605] can: broadcast manager protocol (rev 20170425 t)
[    0.798229] can: netlink gateway (rev 20170425) max_hops=1
[    0.803777] NET: Registered protocol family 36
[    0.808103] Key type dns_resolver registered
[    0.812697] registered taskstats version 1
[    0.816397] Loading compiled-in X.509 certificates
[    0.823213] zynqmp-pinctrl pinctrl: zynqmp pinctrl initialized
**[    0.828138] zynqmp_clock: probe of clk failed with error -22**
[    0.834279] zynqmp_power zynqmp-power: Failed to request rx channel
[    0.838802] zynqmp_power: probe of zynqmp-power failed with error 1
[    0.845242] cdns-spi ff040000.spi: pclk clock not found.
[    0.855477] xilinx-zynqmp-dma fd500000.dma: ignoring dependency for device, assuming no driver
[    0.859052] xilinx-zynqmp-dma fd510000.dma: ignoring dependency for device, assuming no driver
[    0.867611] xilinx-zynqmp-dma fd520000.dma: ignoring dependency for device, assuming no driver
[    0.876174] xilinx-zynqmp-dma fd530000.dma: ignoring dependency for device, assuming no driver
[    0.884742] xilinx-zynqmp-dma fd540000.dma: ignoring dependency for device, assuming no driver
[    0.893301] xilinx-zynqmp-dma fd550000.dma: ignoring dependency for device, assuming no driver
[    0.901868] xilinx-zynqmp-dma fd560000.dma: ignoring dependency for device, assuming no driver
[    0.910432] xilinx-zynqmp-dma fd570000.dma: ignoring dependency for device, assuming no driver
[    0.919031] cdns-spi ff040000.spi: pclk clock not found.
[    0.924272] zynqmp-qspi ff0f0000.spi: ignoring dependency for device, assuming no driver
[    0.932788] macb ff0b0000.ethernet: ignoring dependency for device, assuming no driver
[    0.940730] macb ff0e0000.ethernet: ignoring dependency for device, assuming no driver
[    0.948697] dwc3-of-simple ff9d0000.usb0: ignoring dependency for device, assuming no driver
[    0.956747] cdns-i2c ff020000.i2c: ignoring dependency for device, assuming no driver
[    0.964788] sdhci-arasan ff160000.sdhci: ignoring dependency for device, assuming no driver
[    0.972817] sdhci-arasan ff170000.sdhci: ignoring dependency for device, assuming no driver
[    0.981224] xuartps ff000000.serial: ignoring dependency for device, assuming no driver
[    0.988830] zynq-gpio ff0a0000.gpio: ignoring dependency for device, assuming no driver
[    0.998694] rtc_zynqmp ffa60000.rtc: setting system clock to 1970-01-01 00:37:33 UTC (2253)
[    1.004893] of_cfs_init
[    1.007312] of_cfs_init: OK
[    1.010245] Warning: unable to open an initial console.
[    1.015409] Waiting for root device ...

Thank you once again!

**Comment by tholzsche** [comment]
Hi, I would not recommend to simply use the XU1 device-tree. I would build on an existing device-tree in the analog-deivce kernel (zcu102) and just make the necessary adjustments "aliases", "gem", "sdhci1"... Hopefully this will help.

**Comment by flpm2** [comment]
Managed to run latest ad linux master after I recompiled xilinx atf to latest master. Thank you for the support.
