### ISSUE TITLE
only eth0 can work? how to config it make both eth0 and eth1 work

### ISSUE THREAD

**Issue by wangyuanzhengbighead** [enclustra-bsp/bsp-xilinx#32]
I use petalinux2020 to generate the kernel, my baseboard is "pe1 + xu15eg",i add some infomation in system-user.dtsi. but the eth1 also not work.what should i do?
![01](https://user-images.githubusercontent.com/38694798/103495841-0e203a80-4e77-11eb-8acd-54111dd7c5e1.png)
![02](https://user-images.githubusercontent.com/38694798/103495845-0f516780-4e77-11eb-8630-fd49fd60cfb8.png)
[startlog.txt](https://github.com/enclustra-bsp/bsp-xilinx/files/5762735/startlog.txt)
[system-userdtsi.txt](https://github.com/enclustra-bsp/bsp-xilinx/files/5762736/system-userdtsi.txt)

**Comment by tholzsche** [comment]
Hi. The mdio interface is shared between gem0 and gem3. The device tree should look like below. We will soon release petalinux BSPs based on 2020.1. Please contact our support for a preliminary release. Greets
```
&gem0 {
	status = "okay";
	/delete-property/ local-mac-address;
	phy-mode = "rgmii-id";
	phy-handle = <&phy0>;
	phy0: phy@3 {
		reg = <3>;

		txc-skew-ps = <1800>;
		txen-skew-ps = <420>;

		txd0-skew-ps = <420>;
		txd1-skew-ps = <420>;
		txd2-skew-ps = <420>;
		txd3-skew-ps = <420>;

		rxc-skew-ps = <900>;
		rxdv-skew-ps = <420>;

		rxd0-skew-ps = <420>;
		rxd1-skew-ps = <420>;
		rxd2-skew-ps = <420>;
		rxd3-skew-ps = <420>;		
	};
	phy1: phy@7 {
		reg = <7>;

		txc-skew-ps = <1800>;
		txen-skew-ps = <420>;

		txd0-skew-ps = <420>;
		txd1-skew-ps = <420>;
		txd2-skew-ps = <420>;
		txd3-skew-ps = <420>;

		rxc-skew-ps = <900>;
		rxdv-skew-ps = <420>;

		rxd0-skew-ps = <420>;
		rxd1-skew-ps = <420>;
		rxd2-skew-ps = <420>;
		rxd3-skew-ps = <420>;		
	};
};
```

**Comment by wangyuanzhengbighead** [comment]
thanks, it works
