### ISSUE TITLE
No uImage when building for XU1 & PE1

### ISSUE THREAD

**Issue by thetemplar** [enclustra-bsp/bsp-xilinx#4]
Hello,
I have two boards for my PE1 Baseboard: A (Zynq7000) ZX1 and a (Ultrascale) XU1.
I used this guide: http://enclustra.github.io/ebe-docs/user-doc-xilinx/index_xilinx.html
Building for the ZX1 was no problem at all (although having trouble with the USB phy).

Building for the XU1 produces no uImage though, only this files:
```
 bl31.elf
 boot.bif
 boot.bin
 configs
 devicetree.dtb
 fpga.bit
 fsbl.elf
 Image
 pmu.elf
 rootfs.tar
 u-boot.elf
 uboot.scr
 uboot_ramdisk.scr
 uramdisk
```

Previously I copied boot.bin, devicetree.dtb, uboot.scr and uImage to the boot-partition and it worked perfectly.
Now I have no "uImage" (only "Image"), both are not working, my board is stuck at the FSBL saying

```
Xilinx Zynq MP First Stage Boot Loader
Release 2017.1   May 18 2017  -  12:41:12
```

**Comment by LinhDNguyen** [comment]
Maybe you should double check the wiki again, for XU1, only Image available (http://enclustra.github.io/ebe-docs/user-doc-xilinx/index_xilinx.html#sd-card-mmc) and that file will be used (instead of uImage).

I follow the guide line, using XU1 15EG, SD card and everything work fine.
