### ISSUE TITLE
Problems with SD boot on Mercury XU8 and Mercury PE1

### ISSUE THREAD

**Issue by sombresleep** [enclustra-bsp/bsp-xilinx#45]
I think my problem is similar to #11 , but the solution from there isn't working for me.

I want to boot from my SD card with Linux that I generated using Enclustra BSP and see the U-boot UART console via USB. But when I power up my board, the PC doesn't even see the Serial device.

What postilions of dip switches and voltage jumpers should I choose to make it work? The manual isn't clear enough for me.

Enclustra support hasn't responded (yet?).

UPD: Some extra informations:

* CFG A 0001
* CFG B 1011
* Vsel A =>B
* Vsel B =>B

LEDs:

* PWGD - on
* DONE -on
* TX - sometimes blinking
* SC - constanly blinking if the miscro usb is connected
* CPU - off

No serial device is seen in the Windows device manager

**Comment by andreas-buerkler-enclustra** [comment]
The Linux build scripts use the binaries of our Vivado reference designs. All required steps to setup the hardware can be found in the "getting started" section of the reference design manual (https://github.com/enclustra/Mercury_XU8_PE1_Reference_Design/blob/master/reference_design/doc/Mercury_XU8_PE1.pdf). Your DIP switch settings are different compared to the reference design manual, but they work as well. Only the USB PHY on XU8 is connected differently. If DIP switch CFG B 2 is set to "off" position, then the USB signals of the USB-UART converter are routed to the micro USB connector (labelled as USBUB). It might be required to activate the virtual COM port setting in Windows (see section "UART connection issues" in the reference design manual).

**Comment by sombresleep** [comment]
@andreas-buerkler-enclustra Thank you for your response!

I managed to get it work. The missing piece of the puzzle for me was this:

```
﴾d﴿ Select FTDI Configuration.
﴾e﴿ Select Xilinx JTAG as the device mode.
﴾f﴿ Click Set device mode.
```

After changing the device mode to Xilinx JTAG, the serial port appeared in the device list.

![image](https://github.com/user-attachments/assets/b020e3c1-ee22-4c72-9e9b-26382ed5e7f9)

Hurray!

**Comment by sombresleep** [comment]
Issue resolved
