### ISSUE TITLE
arm-none-linux-gnueabi toolchain is missing sysroot support

### ISSUE THREAD

**Issue by andreca** [enclustra-bsp/bsp-xilinx#9]
1.7 version of the arm-none-linux-gnueabi toolchain has not been built with "--with-sysroot".

Without sysroot support the CMake "toolchain-file" cross-compilation strategy doesn't work. The value of CMAKE_SYSROOT will have no effect and makes cross-compilation more challenging.

Could this be added to the toolchain?

**Comment by joannabrozek** [comment]
Hi @andreca,

The toolchain distributed with EBE is meant for building U-Boot and Linux kernel so it does not include systroot. The build system generates a toolchain tailored for the rootfs during the build process. You can find it in `sources/buildroot-rootfs/output/host/` within bsp directory.
